### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'my_db_name.admin_mypage' doesn't exist")

### ISSUE THREAD

**Issue by zhaolh1** [idlesign/django-etc#8]
Hi! 
I'm a self-taught programmer and now working on a small app which is using by my classmates. I manage the database through Django Admin. 
Because there are several models in this app, when I try to input data, I need to input data in multiple models, it's boring and very easy to make mistakes.
So I want to have a page where I can input all data here, and directly distribute them to the proper model by click the Save button.
I used the django-etc, I found that it is very easy to make a new page in admin site, there are input box or text area and so on...your work is excellent!  
While developing, I want to check the data in terminal first, but I got an error:
django.db.utils.ProgrammingError: (1146, "Table 'my_db.admin_mypage' doesn't exist")

here is my code:

```
class MyPage(CustomModelPage):
    title = 'Add Collection and Info'  # set page title

    # Define some fields.
    collection_title = models.CharField(unique=True)
    collection_description = models.TextField(blank=True)
    collection_remark = models.CharField(blank=True)
    collection_released_at = models.DateTimeField()
    collection_is_active = models.BooleanField(default=False)
    info_bulk_content = MDTextField(blank=True)
    ......

    admin_cls = MyPageModelAdmin  # set admin class for this page

    def save(self):
        print(self.collection_title)
        pass
        # self.bound_admin.message_success(self.bound_request, f'Hey, done!')
        # print(11111111111111111111111111111111111111111111111111111111111111)
        # super().save()
```

How can I fixed this? I hope that the fields starts with "collection_" can go to Collection Model, the fields starts with "info_" can go to Info Model, and also make some links....

Any help is highly appricated. Thank you!

**Comment by idlesign** [comment]
Hi,

> While developing, I want to check the data in terminal first, but I got an error:

And what do you do precisely in terminal (what commands do you use)?
What's the traceback?

**Comment by zhaolh1** [comment]
> Hi,
> 
> > While developing, I want to check the data in terminal first, but I got an error:
> 
> And what do you do precisely in terminal (what commands do you use)? What's the traceback?

```
[07/Nov/2022 13:48:03] "GET /contributor/admin/mypage/ HTTP/1.1" 200 16872
[07/Nov/2022 13:48:07] "GET /contributor/admin/mypage/ HTTP/1.1" 200 16872
[07/Nov/2022 13:48:07] "GET /contributor/jsi18n/ HTTP/1.1" 200 8398
Internal Server Error: /contributor/admin/mypage/
Traceback (most recent call last):
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'paperor_rds_v3.admin_mypage' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func  
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\etc\admin\admins.py", line 73, in view_custom
    return self._changeform_view(request, object_id=None, form_url='', extra_context=context)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\contrib\admin\options.py", line 1791, in _changeform_view   
    form_validated = form.is_valid()
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\forms\forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\forms\forms.py", line 200, in errors
    self.full_clean()
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\forms\models.py", line 498, in _post_clean
    self.validate_unique()
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\forms\models.py", line 507, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\base.py", line 1173, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\base.py", line 1280, in _perform_unique_checks    
    if qs.exists():
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\query.py", line 892, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\sql\query.py", line 589, in has_results
    return compiler.has_results()
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1329, in has_results       
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql       
    cursor.execute(sql, params)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers   
    return executor(sql, params, many, context)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Z\Zcode\paperor_drf\venv\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'paperor_rds_v3.admin_mypage' doesn't exist")
[07/Nov/2022 13:48:12] "POST /contributor/admin/mypage/ HTTP/1.1" 500 202542
```

I am a self-taught programmer, I developed this app by google from zero, if this is a stupid question, please forgive me...

**Comment by idlesign** [comment]
Seems like ORM wants a table in the database, despite the fact that a model (internally used for your admin page) is marked both as abstract and unmanaged.

I'm unable to reproduce it yet, maybe it's somehow related to mysql.
What django version do you use?

> if this is a stupid question, please forgive me...

No need to excuse: questions are welcome.

**Comment by zhaolh1** [comment]
Here is the version:
Python:3.8.5
Django:  4.0.6
django-etc:1.4.0
mysqlclient: 2.1.1
......

> despite the fact that a model (internally used for your admin page) is marked both as abstract and unmanaged.

I tried to run a migration command, and Django wants to create a new table:

```
(venv) PS C:\Users\Z\Zcode\paperor_drf> py .\manage.py makemigrations
Migrations for 'admin':
  venv\lib\site-packages\django\contrib\admin\migrations\0004_mypage.py
    - Create model MyPage
```

**Comment by zhaolh1** [comment]
I solved this problem by removing the `unique=True` argment...

```
from django.db import models
from etc.admin import CustomModelPage, admins

class MyPageModelAdmin(admins.CustomPageModelAdmin):

    fields = (
        'collection_title',
    )


class MyPage(CustomModelPage):

    title = 'Add Collection'  # set page title

    # Define some fields.
    # collection_title = models.TextField(unique=True) ####!!! won't work !!!####
    collection_title = models.TextField()  ####!!! will work !!!####

    admin_cls = MyPageModelAdmin  # set admin class for this page

    def save(self):
        print(self.collection_title)
        pass
        # self.bound_admin.message_success(self.bound_request, f'Hey, done!')
        # print(11111111111111111111111111111111111111111111111111111111111111)
        # super().save()

# Register my page within Django admin.
MyPage.register()
```
